### ISSUE TITLE
Is it possible to extract msgid and msgstr as the same function argument?

### ISSUE THREAD

**Issue by EdwardDrapkin** [jruchaud/babel-gettext-plugin#3]
Hey, I have a function called t() that I was planning on just passing a string to like "hello world".  I've got to the point where t("hello world") extracts into a msgid of "hello world" with an empty msgstr, but is it possible to have the output file have the same msgstr as msgid?

**Comment by jruchaud** [comment]
Hello

Not yet, but we can add a parameter to have msgstr as msgid. It suits you ?

**Comment by jruchaud** [comment]
Ok done in version 2.1.0. Could you confirm ?

**Comment by EdwardDrapkin** [comment]
Wow dude, fast and helpful!

Thank you so much this is perfect!

**Comment by jruchaud** [comment]
You're welcome.
