### ISSUE TITLE
msgid_plural

### ISSUE THREAD

**Issue by arstiefel** [jruchaud/babel-gettext-plugin#6]
Hi, 

I was just wondering how to set up msgid_plural in conjunction with msgid. Thanks

**Comment by jruchaud** [comment]
Hello

I thinks this link can help you: https://github.com/alexanderwallin/node-gettext

Do you use this in your code ?
`ngettext(msgid, msgid_plural, count)`

Regards

**Comment by arstiefel** [comment]
Yeah, I figured it out. Thanks
