### ISSUE TITLE
Not extracting all strings with _t

### ISSUE THREAD

**Issue by arstiefel** [jruchaud/babel-gettext-plugin#7]
The plugin when running as a plugin in babelrc does not seem to be picking up all instances of _t. It in fact seems completely random on how many it will pick up. Sometimes 20, sometimes 50, 70, etc.

**Comment by jruchaud** [comment]
Hello

I never use the plugin with babelrc. I probably babelrc transpile only the part have changed so the plugin get only the string on the changed part. Could you confirm the issue ?

**Comment by arstiefel** [comment]
How do you use it to transpile a whole project?

**Comment by jruchaud** [comment]
With node or gulp or grunt or command line.

**Comment by arstiefel** [comment]
Switching to gulp I am still having the same problem

**Comment by jruchaud** [comment]
Do you have a test which I can see the issue ?

**Comment by arstiefel** [comment]
I don't, really. This is my gulpfile

```
const gulp = require( 'gulp' );
const babel = require( 'gulp-babel' );

gulp.task( 'default', () => {
  return gulp.src( 'app/**/*.js' )
    .pipe( babel( {
      presets: [ 'babel-preset-react' ],
      plugins: [ "transform-decorators-legacy",
        [ "babel-gettext-plugin",
          {
            "functionNames": {
              "_t": [
                "msgid"
              ],
              "_nt": [
                "msgid",
                "msgid_plural",
                "count"
              ]
            },
            "fileName": "./test/output.po"
          }
        ]
      ]
    } ) )
    .pipe( gulp.dest( 'dist' ) );
} );
```

I have a couple hundred `_t`'s throughout my code and the output.po only has about 90 lines in it

**Comment by arstiefel** [comment]
Oh, never mind. I think it's working
