### ISSUE TITLE
Question: NPM 3.0.0 published - but no github release with this tag

### ISSUE THREAD

**Issue by iongion** [jruchaud/babel-gettext-plugin#9]
Are there any breaking changes from the 2.x series ?
Is it possible to add a CHANGELOG.md file documenting the changes for an easier upgrade path ?

Thank you, this is so useful for my projects!

**Comment by jruchaud** [comment]
Hello

I have just updated the dependencies for Babel 7, so we have normaly no breaking changes.

I will add the CHANGELOG.md.

Julien

**Comment by iongion** [comment]
Awesome, many thanks!
